var LOCAL_STORAGE_GLOBAL_KEY = 'FINANCE_APP';

var LOCAL_STORAGE_CATEGORIES_KEY = `${LOCAL_STORAGE_GLOBAL_KEY}_CATEGORIES`;
var LOCAL_STORAGE_EXPENSE_CALENDAR_KEY = `${LOCAL_STORAGE_GLOBAL_KEY}_EXPENSE_CALENDAR`

export {
  LOCAL_STORAGE_GLOBAL_KEY, 
  LOCAL_STORAGE_CATEGORIES_KEY, 
  LOCAL_STORAGE_EXPENSE_CALENDAR_KEY 
};